### ISSUE TITLE
My host doesn't have "gmp_import()". Workaround?

### ISSUE THREAD

**Issue by matt-matt1** [bseddon/ocsp-responder#2]
Error:
Fatal error: Uncaught Error: Call to undefined function gmp_import() in .../vendor/lyquidity/requester/src/Asn1/Util/BigInteger.php:67

This error message doesn't appear on my home computer.  So I gather the host disabled "gmp_import()" (may be for security reasons...).
Is there a way to accomplish the same with another function (perhaps many) ?

**Comment by bseddon** [comment]
The same question was asked [here](https://github.com/bseddon/requester/issues/2).  It's not an issue I have any interest resolving.  The code was created for my OCSP implementation and made public in case other wish to use it.  Your choices are to:

* find another implementation,
* create an implementation of BigInteger that can work in your environment, 
* install GMP, or, 
* if your host will not permit that, use a different provider

Good luck.
